import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const usersData = [
	{
		first_name: 'Satyam',
		last_name: 'Kulkarni',
		username: 'https://pbs.twimg.com/profile_images/1508937780084318214/pcjY-hFq_400x400.jpg',
	},
	{
		first_name: 'Satyam',
		last_name: 'Kulkarni',
		username: 'https://pbs.twimg.com/profile_images/1508937780084318214/pcjY-hFq_400x400.jpg',
	},
	{
		first_name: 'Satyam',
		last_name: 'Kulkarni',
		username: 'https://pbs.twimg.com/profile_images/1508937780084318214/pcjY-hFq_400x400.jpg',
	},
]

const NewPeople = () => {
	const [users, setUsers] = useState(usersData)

	useEffect(() => {
		fetch('http://localhost:5000/users/')
			.then(data => data.json()).then(json => setUsers(json.users))
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>Connect Pe</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.main}>
				<div className={styles.grid}>
					{users && users.map(user => (
						<div className={styles.card}>
							<img src={user.username} />
							<h1>{user.first_name} {user.last_name}</h1>
						</div>
					))}
				</div>
			</div>

			<footer>
				<a
				href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
				target="_blank"
				rel="noopener noreferrer"
				>
				Powered by
				DY Patil Students
				</a>
			</footer>
		</div>
	)
}

export default NewPeople